// Generated by https://quicktype.io

export interface AllBalances {
    data: AllBalanceData[];
}

export interface AllBalanceData {
    BalanceID: number;
    Time:      string;
    StudentID: number;
    FirstName: string;
    LastName:  string;
    Room:      string;
    Amount:    number;
    Name:      string;
    LogType:   string;
    HallName:  string;
    HallID:    number;
    Currency:  string;
}
