// Generated by https://quicktype.io

export interface Balance {
    data: BalanceData[];
}

export interface BalanceData {
    id:        number;
    StudentID: number;
    Type:      string;
    TypeID:    number;
    Amount:    number;
    Time:      number;
}
