// Generated by https://quicktype.io

export interface Cards {
    data: Datum[];
}

export interface Datum {
    id:      number;
    Title:   string;
    Tag:     string;
    TagType: string;
    Buttons: string;
}
