// Generated by https://quicktype.io

import { HomeButton } from "./card-button.interface";

export interface Cards {
    data: Datum[];
}

export interface Datum {
    id:      number;
    Title:   string;
    Tag:     string;
    TagType: string;
    BGColor: string;
    PrimaryLink: string;
    Button1: HomeButton;
    Button2: HomeButton;
    Button3: HomeButton;
}
