// Generated by https://quicktype.io

export interface EarnableCurrency {
    data: EarnableCurrencyData[];
}

export interface EarnableCurrencyData {
    id:        number;
    Hall:      number;
    Amount:    number;
    Name:      string;
    Shortened: string;
    Hash:      string;
}
