// Generated by https://quicktype.io

export interface Hall {
    data: Datum[];
}

export interface Datum {
    id:          number;
    Name:        string;
    Shortened:   string;
    Currency:    string;
    Mascot:      string;
    ActiveCards: string;
}
