// Generated by https://quicktype.io

export interface Profile {
    base:   Base;
    emails: Email[];
}

export interface Base {
    Name:     string;
    Email:    string;
    Username: string;
}

export interface Email {
    Email: string;
}
