// Generated by https://quicktype.io

export interface Registration {
  data: Data;
}

export interface Data {
  base:   Base[];
  access: Access[];
}

export interface Access {
  id:   number;
  Name: string;
}

export interface Base {
  id:     number;
  Access: number;
  Hash:   string;
  Hall:   string;
  Active: number;
}
