// Generated by https://quicktype.io

export interface Registration {
  data: Data;
}

export interface Data {
  base:   Base[];
}

export interface Base {
  HallName: string;
  AccessName: string;
  AccessLevel: number;
  HallId: number;
}
