// Generated by https://quicktype.io

export interface Resident {
    data: ResidentData[];
}

export interface ResidentData {
    id:         number;
    FirstName:  string;
    LastName:   string;
    CardNumber: string;
    HallID:     number;
    Room:       string;
}
