// Generated by https://quicktype.io

export interface Study {
    data: StudyArray[];
}

export interface StudyArray {
    StaffName: string;
    Reason:    string;
    StudyID:   number;
    StaffID:   number;
    StudentID: number;
    FirstName: string;
    LastName:  string;
    StartDate: string;
    EndDate:   string;
    HallID:    number;
}
