// Generated by https://quicktype.io

export interface Student {
    data: Datum[];
}

export interface Datum {
    id:         number;
    FirstName:  string;
    LastName:   string;
    CardNumber: string;
}
