// Generated by https://quicktype.io

export interface Study {
    data: StudyArray[];
}

export interface StudyArray {
    id:         number;
    StaffID:    number;
    StudentID:  number;
    HallID:     number;
    Reason:     string;
    StartDate:  string;
    EndDate:    null;
    FirstName:  string;
    LastName:   string;
    CardNumber: string;
}
