// Generated by https://quicktype.io

export interface Study {
    data: StudyArray[];
}

export interface StudyArray {
    StaffName:      string;
    Reason:         string;
    StudyID:        number;
    StaffID:        number;
    StudentID:      number;
    FirstName:      string;
    LastName:       string;
    StartDate:      string;
    EndDate:        string;
    HallID:         number;
    dateDifference: DateDifference;
}

export interface DateDifference {
    days:    number;
    hours:   number;
    minutes: number;
    seconds: number;
}
